# Generated by Django 4.1.3 on 2023-03-27 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
