# Generated by Django 4.1.3 on 2023-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registrationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orcid',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rinc_auth_id',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scorpus_auth_id',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spin_kod',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wos_id',
            field=models.PositiveIntegerField(blank=True, default='1'),
        ),
    ]
