const About = () => {
 return (
  <div>
    <h1>О нас</h1>
      <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Quisque non tellus orci ac auctor. Suspendisse sed nisi lacus sed viverra tellus in. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Vel pharetra vel turpis nunc eget. Sagittis orci a scelerisque purus semper eget. Sapien eget mi proin sed libero. In arcu cursus euismod quis viverra. Sagittis vitae et leo duis ut diam quam nulla. Gravida quis blandit turpis cursus in hac. Eget magna fermentum iaculis eu non diam phasellus. In ante metus dictum at tempor commodo ullamcorper a. Semper eget duis at tellus at urna condimentum mattis. Sit amet commodo nulla facilisi. Vel orci porta non pulvinar neque.

          Pretium lectus quam id leo in vitae turpis massa. Magna ac placerat vestibulum lectus mauris ultrices. Lacus viverra vitae congue eu consequat. Volutpat lacus laoreet non curabitur gravida arcu ac. Mauris rhoncus aenean vel elit. Morbi non arcu risus quis varius quam quisque id. At urna condimentum mattis pellentesque id nibh tortor id. At elementum eu facilisis sed odio morbi quis commodo. Feugiat sed lectus vestibulum mattis ullamcorper. Euismod lacinia at quis risus sed vulputate odio ut. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Lorem ipsum dolor sit amet. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Eu consequat ac felis donec et.

          Mattis nunc sed blandit libero volutpat sed cras ornare. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Ultrices gravida dictum fusce ut. In massa tempor nec feugiat. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Sem integer vitae justo eget magna. Odio euismod lacinia at quis. Mauris cursus mattis molestie a iaculis. Vitae tempus quam pellentesque nec nam aliquam sem. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Posuere ac ut consequat semper viverra nam libero justo laoreet. Ut tellus elementum sagittis vitae et. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Quam id leo in vitae turpis. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Amet cursus sit amet dictum sit. Faucibus nisl tincidunt eget nullam. Et netus et malesuada fames ac. Feugiat scelerisque varius morbi enim nunc faucibus a.

          Morbi leo urna molestie at elementum eu facilisis. Id porta nibh venenatis cras sed. Ut consequat semper viverra nam. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Tempus iaculis urna id volutpat lacus. Nec feugiat in fermentum posuere urna nec. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Eget duis at tellus at urna condimentum. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Ipsum suspendisse ultrices gravida dictum fusce ut placerat. In vitae turpis massa sed elementum. Facilisi nullam vehicula ipsum a. Ultrices vitae auctor eu augue. Phasellus faucibus scelerisque eleifend donec pretium. Amet risus nullam eget felis eget nunc lobortis. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Dignissim sodales ut eu sem integer. Egestas dui id ornare arcu odio ut sem nulla.
          Tellus mauris a diam maecenas sed enim ut sem. Posuere ac ut consequat semper viverra nam libero justo. Malesuada fames ac turpis egestas sed. Odio tempor orci dapibus ultrices in iaculis nunc sed. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Diam maecenas sed enim ut sem viverra. Lacus viverra vitae congue eu. Diam quis enim lobortis scelerisque fermentum. Eros in cursus turpis massa tincidunt dui ut ornare. Nisi est sit amet facilisis magna etiam. In vitae turpis massa sed. Tincidunt eget nullam non nisi est. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Sit amet commodo nulla facilisi.</div>
  </div>
 );
};

export default About;
