# Generated by Django 4.1.3 on 2022-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.CharField(blank=True, max_length=4)),
                ('keywords', models.TextField(blank=True)),
                ('output_data', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('tome', models.CharField(blank=True, max_length=255)),
                ('issue_number', models.CharField(blank=True, max_length=255)),
                ('pages', models.CharField(blank=True, max_length=255)),
                ('details_of_documents', models.TextField(blank=True)),
                ('udk', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='publications/files/%Y/%m/%d')),
            ],
        ),
    ]
