# Generated by Django 4.1.3 on 2022-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
