# Generated by Django 4.1.3 on 2023-03-31 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='DOI',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='ISBN',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='ISSN',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='RINC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='WoS_CC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='affil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_publ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='e_ISSN',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='elib_ID',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='finans',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='if_index_export',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publ_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='qwart_izd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
    ]
